version: '3.8'

services:
  kaffepause_api:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    container_name: kaffepause_api
    command: /start
    volumes:
      - .:/app
    env_file:
      - .envs/.local/.fastapi
    ports:
      - '8000:8000'

  neo4j:
    image: neo4j:5.4-enterprise
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    expose:
      - 7474
      - 7687
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    env_file:
      - ./.envs/.local/.neo4j

volumes:
  local_neo4j_data: {}
