version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env.local
    ports:
      - '8000:8000'

  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - '5432:5432'
