#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

neo4j_ready() {
python << END
import sys

from neo4j import GraphDatabase
from neo4j.exceptions import ServiceUnavailable

try:
    uri = "neo4j://${NEO4J_HOST}:${NEO4J_PORT}"
    auth = ("${NEO4J_USER}", "${NEO4J_PASSWORD}")
    driver = GraphDatabase.driver(uri, auth=auth)
    driver.verify_connectivity()
except ServiceUnavailable:
    sys.exit(-1)
sys.exit(0)

END
}
until neo4j_ready; do
  >&2 echo 'Waiting for Neo4j to become available...'
  sleep 1
done
>&2 echo 'Neo4j is available'

exec "$@"
